# Moving Average Crossover Strategy Parameter Space

parameters:
  - name: fast_period
    type: integer
    min: 5
    max: 50
    step: 5
    description: "Fast moving average period"

  - name: slow_period
    type: integer
    min: 20
    max: 200
    step: 20
    description: "Slow moving average period"

  - name: position_size
    type: float
    min: 50
    max: 500
    step: 50
    description: "Position size in shares"

  - name: use_trailing_stop
    type: boolean
    description: "Whether to use trailing stop"

  - name: stop_loss_pct
    type: float
    min: 0.01
    max: 0.1
    num_points: 5
    description: "Stop loss percentage"
