backtest:
  data_dir: ./data
  data_source: csv
  end_date: '2024-12-31'
  initial_capital: 100000.0
  start_date: '2024-01-01'
  symbols:
  - SPY
  timeframe: 1min
broker:
  commission: 0.0005
  slippage: 0.0001
data:
  custom_data:
    file: HEAD_1min.csv
    symbol_column: null
  data_dir: ./data
  source_type: csv
  timestamp_column: date
logging:
  components:
  - strategy.implementations.ma_crossover
  - execution.order_registry
  - execution.order_manager
  - execution.backtest.backtest
  - risk.managers.simple
  level: DEBUG
risk:
  max_position_pct: 1.0
  position_size: 500
strategy:
  parameters:
    fast_window: 2
    price_key: close
    slow_window: 5
  type: ma_crossover
