# config/optimization_test.yaml
backtest:
  initial_capital: 100000.0
  symbols: ['HEAD']  # Use the symbol that matches your data file
  timeframe: "1min"  # Make sure this matches your data file's timeframe
  data_source: "csv"
  data_dir: "./data"
  start_date: "2023-01-01"
  end_date: "2024-12-31"

strategies:
  ma_crossover:
    enabled: true
    price_key: "close"
    # Make sure to include the symbols here too
    symbols: ['HEAD']  
    # Default parameters
    fast_window: 10
    slow_window: 30

risk_manager:
  position_size: 100
  max_position_pct: 0.1
  
optimization:
  enabled: true
  method: "grid_search"
  max_evaluations: 50
  max_time: 600
  objective: "sharpe_ratio"
  maximize: true
  
  parameter_space:
    ma_crossover:
      fast_window:
        type: "integer"
        min: 2
        max: 20
        step: 1
      slow_window:
        type: "integer"
        min: 10
        max: 50
        step: 5
      price_key:
        type: "categorical"
        options: ["open", "high", "low", "close"]

  random_search:
    seed: 42
    num_samples: 30

  output:
    save_results: true
    results_dir: "./optimization_results"
    plot_top_n: 5
