# Configuration for testing the refactored architecture
# ------------------------------------------------------

# Global backtest settings
backtest:
  initial_capital: 100000.0
  symbols: ['MINI']
  data_dir: "./data"
  timeframe: "1min"
  data_source: "csv"
  start_date: "2024-01-01"
  end_date: "2024-12-31"
  strategy: "simple_ma_crossover"  # Important: Use our new implementation

# Data handling configuration
data:
  source_type: "csv"
  data_dir: "./data"
  file_pattern: "{symbol}_{timeframe}.csv"
  timestamp_column: "timestamp"
  price_columns:
    open: "Open" 
    high: "High"
    low: "Low"
    close: "Close"
    volume: "Volume"

# Strategy configuration
strategies:  
  simple_ma_crossover:  # Match the name in our SimpleMACrossoverStrategy class
    enabled: true
    fast_window: 5
    slow_window: 15
    price_key: "close"

# Risk management settings
risk_manager:
  type: "enhanced"  # Use our new enhanced risk manager
  position_sizing_method: "fixed"
  position_size: 100
  max_position_size: 1000
  max_position_pct: 0.1
  max_risk_per_trade: 0.01
  
# Order handling settings
order_manager:
  default_order_type: "MARKET"

# Broker simulation settings
broker:
  slippage: 0.001
  commission: 0.001
  delay: 0

# Performance metrics settings
performance:
  metrics:
    - "total_return"
    - "sharpe_ratio"
    - "max_drawdown"
    - "win_rate"
    - "profit_factor"
  
# Logging settings
logging:
  level: "INFO"