# Regime Ensemble Strategy Optimization Configuration
# This configuration is designed to optimize the regime-based ensemble strategy with SPY 1-minute data

# Use 'backtest' mode with optimization flag
mode: backtest

# Basic settings
backtest:
  initial_capital: 100000.0
  symbols: ['SPY']
  timeframe: "1min"
  optimize: true  # Enable optimization mode

# Data configuration
data:
  source_type: csv
  date_column: timestamp
  date_format: "%Y-%m-%d %H:%M:%S"
  sources:
    - symbol: SPY
      file: data/SPY_1min.csv
      price_column: close
  
  # Train/test split configuration (70% train, 30% test)
  train_test_split:
    method: ratio
    train_ratio: 0.7
    test_ratio: 0.3

# Initial capital
initial_capital: 100000.0

# Strategy configuration
strategy:
  name: regime_ensemble
  # Define default parameters (will be used as starting point for optimization)
  default_params:
    # Regime detection parameters
    volatility_window: 60
    volatility_threshold: 0.002
    trend_ma_window: 120
    trend_threshold: 0.01
    
    # Strategy parameters - Trend following
    fast_ma_window: 20
    slow_ma_window: 60
    
    # Strategy parameters - Mean reversion
    rsi_window: 30
    rsi_overbought: 70
    rsi_oversold: 30
    
    # Strategy parameters - Volatility breakout
    breakout_window: 60
    breakout_multiplier: 1.5
    
    # Regime weights
    regime_weights:
      trend:
        trend_following: 1.0
        mean_reversion: 0.2
        volatility_breakout: 0.5
      mean_reversion:
        trend_following: 0.2
        mean_reversion: 1.0
        volatility_breakout: 0.3
      volatile:
        trend_following: 0.3
        mean_reversion: 0.3
        volatility_breakout: 1.0
      neutral:
        trend_following: 0.5
        mean_reversion: 0.5
        volatility_breakout: 0.5

# Optimization settings
optimization:
  method: grid  # grid, random or walk_forward
  objective: train_test_combined  # Special objective that combines train and test performance
  train_weight: 0.4  # Weight for training performance
  test_weight: 0.6   # Weight for test performance (higher to prevent overfitting)
  sub_objective: sharpe_ratio  # Metric used for both train and test evaluation
  output_dir: ./optimization_results

# Parameter space file (optional - if commented out, will use inline parameter_space)
# parameter_file: config/parameter_spaces/regime_ensemble_params.yaml

# Parameter space definition for optimization
parameter_space:
  # Regime detection parameters
  - name: volatility_window
    type: integer
    min: 30
    max: 120
    step: 30
    description: "Volatility calculation window"

  - name: trend_ma_window
    type: integer
    min: 60
    max: 240
    step: 60
    description: "Moving average window for trend detection"

  # Strategy parameters - Trend following
  - name: fast_ma_window
    type: integer
    min: 10
    max: 40
    step: 10
    description: "Fast moving average window"

  - name: slow_ma_window
    type: integer
    min: 30
    max: 120
    step: 30
    description: "Slow moving average window"

  # Strategy parameters - Mean reversion
  - name: rsi_window
    type: integer
    min: 14
    max: 50
    step: 12
    description: "RSI calculation window"

  - name: rsi_overbought
    type: integer
    min: 65
    max: 80
    step: 5
    description: "RSI overbought threshold"

  - name: rsi_oversold
    type: integer
    min: 20
    max: 35
    step: 5
    description: "RSI oversold threshold"

  # Strategy parameters - Volatility breakout
  - name: breakout_window
    type: integer
    min: 20
    max: 100
    step: 20
    description: "Volatility breakout calculation window"

  - name: breakout_multiplier
    type: float
    min: 1.0
    max: 2.5
    step: 0.5
    description: "ATR multiplier for breakout levels"

# Risk management settings
risk:
  position_sizing_method: fixed
  position_size: 100
  max_position_pct: 0.05  # Reduced to 5% for higher frequency
  max_trades_per_hour: 10  # Added to limit excessive trading

# Broker configuration
broker:
  slippage: 
    type: percentage
    amount: 0.0005  # Reduced for more accurate 1-minute simulation
  commission:
    type: percentage
    rate: 0.0005    # Reduced for more frequent trading

# Logging configuration
logging:
  level: INFO
  console: true
  file: true
  file_name: regime_optimization.log