# Simple MA Crossover Optimization Configuration

# Mode
mode: backtest

# Basic settings
backtest:
  initial_capital: 100000.0
  symbols: ['SPY']
  timeframe: "1min"
  optimize: true

# Data configuration
data:
  source_type: csv
  date_column: timestamp
  date_format: "%Y-%m-%d %H:%M:%S"
  sources:
    - symbol: SPY
      file: data/SPY_1min.csv
      price_column: close
  
  # Train/test split configuration (70% train, 30% test)
  train_test_split:
    method: ratio
    train_ratio: 0.7
    test_ratio: 0.3

# Strategy configuration
strategy:
  name: simple_ma_crossover
  default_params:
    fast_window: 20
    slow_window: 50

# Optimization settings
optimization:
  method: grid
  objective: sharpe_ratio
  output_dir: ./optimization_results

# Parameter space definition for optimization
parameter_space:
  - name: fast_window
    type: integer
    min: 5
    max: 25
    step: 5
    description: "Fast moving average window"

  - name: slow_window
    type: integer
    min: 20
    max: 60
    step: 10
    description: "Slow moving average window"

# Broker configuration
broker:
  slippage: 
    type: percentage
    amount: 0.0005
  commission:
    type: percentage
    rate: 0.0005

# Risk management settings
risk:
  position_sizing_method: fixed
  position_size: 100
  max_position_pct: 0.05